---
# tasks file for golang

- name: Download golang
  get_url:
    url: "{{ golang_download_url }}"
    dest: /tmp
    mode: '0644'

- name: Extract golang into {{ golang_path }}
  unarchive:
    src: "{{ golang_zip_path }}"
    dest: "{{ golang_path}}"
    remote_src: yes


- name: Set up golang environment
  lineinfile:
    path: '{{ golang_bash_profile }}'
    line: '{{ item }}'
    insertafter: EOF
  with_items:
    - 'export GOROOT={{ GOROOT }}'
    - 'export GOPATH={{ GOPATH }}'
    - 'export PATH={{ PATH }}'


- name: Update bash profile
  shell: source {{ golang_bash_profile }}
  args:
    executable: /bin/sh

- name: Verify if the golang is installed
  shell: go version
  register: check_go

- debug:
    msg: '{{ check_go }}'
